/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hhty4ii9yHO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"

export function Lander() {
  return (
    <div className="relative w-full h-[80vh] md:h-[90vh] overflow-hidden">
      <div className="absolute inset-0 z-0 flex items-center justify-center">
        <div className="absolute inset-0 bg-gradient-to-r from-primary to-secondary opacity-50 backdrop-blur-lg" />
        <div className="relative z-10 max-w-4xl px-4 md:px-6 lg:px-8 py-12 md:py-16 lg:py-20 text-center">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-primary-foreground mb-4">
            Elevate Your Software Development
          </h1>
          <p className="text-lg md:text-xl lg:text-2xl text-secondary-foreground mb-8">
            Unleash your team's potential with our cutting-edge solutions.
          </p>
          <div className="flex justify-center gap-4">
            <Button size="lg">Learn More</Button>
            <Button variant="secondary" size="lg">
              Get Started
            </Button>
          </div>
        </div>
      </div>
      <Carousel className="w-full h-full">
        <CarouselContent>
          <CarouselItem>
            <img
              src="/placeholder.svg"
              alt="Carousel Image 1"
              className="w-full h-full object-cover opacity-80 transition-opacity duration-1000 ease-in-out"
            />
          </CarouselItem>
          <CarouselItem>
            <img
              src="/placeholder.svg"
              alt="Carousel Image 2"
              className="w-full h-full object-cover opacity-80 transition-opacity duration-1000 ease-in-out"
            />
          </CarouselItem>
          <CarouselItem>
            <img
              src="/placeholder.svg"
              alt="Carousel Image 3"
              className="w-full h-full object-cover opacity-80 transition-opacity duration-1000 ease-in-out"
            />
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious className="absolute top-1/2 left-4 -translate-y-1/2 z-10 text-primary-foreground hover:text-primary transition-colors">
          <ChevronLeftIcon className="w-8 h-8" />
        </CarouselPrevious>
        <CarouselNext className="absolute top-1/2 right-4 -translate-y-1/2 z-10 text-primary-foreground hover:text-primary transition-colors">
          <ChevronRightIcon className="w-8 h-8" />
        </CarouselNext>
      </Carousel>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
